#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
const arg=n=>{const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:null}; const project=path.resolve(arg("--project",".")); const strict=process.argv.includes("--strict"); const supportedThemes=new Set(["scholarly","technical","editorial","high-contrast"]); const errors=[]; const warnings=[]; const check=(ok,msg)=>ok?null:errors.push(msg);
try{const book=JSON.parse(await fs.readFile(path.join(project,"book.json"),"utf8")); const student=await fs.readFile(path.join(project,"dist","textbook.html"),"utf8"); const sol=await fs.readFile(path.join(project,"dist","solutions.html"),"utf8");
 check(student.includes("<!doctype html>"),"student HTML is not a complete document"); check(sol.includes("<!doctype html>"),"solutions HTML is not a complete document"); const theme=arg("--theme")??book.metadata?.theme??"scholarly"; check(supportedThemes.has(theme),`unsupported theme in metadata or override: ${theme}`); check(student.includes(`data-theme="${theme}"`)&&sol.includes(`data-theme="${theme}"`),"selected theme is missing from one or more HTML outputs"); try {const manifest=JSON.parse(await fs.readFile(path.join(project,"dist","manifest.json"),"utf8")); check(manifest.theme===theme,"manifest theme does not match book metadata");} catch {warnings.push("manifest.json not found or invalid theme metadata");} check(!student.includes('class="solution"')&&!student.includes("solution_html"),"student HTML contains solution markers or source fields"); check(!/(?:<script[^>]+src|<link[^>]+href|<img[^>]+src|url\()=["']?https?:\/\//i.test(student+sol),"remote resource found in portable HTML"); check(!/C:\\\\|[A-Z]:\\\\|file:\/\//.test(student+sol),"absolute/local file path found in HTML"); check(!/data-tex=|math-fallback|Replace with|TODO|TBD/i.test(student+sol),"unresolved math or placeholder text found"); check((student.match(/<h2\b/g)||[]).length>=book.chapters.length,"student chapters/headings are incomplete");
 for(const ch of book.chapters){check(student.includes(`id="${ch.id}"`),`missing student chapter ${ch.id}`);check(sol.includes(`id="${ch.id}"`),`missing solution chapter ${ch.id}`);for(const ex of ch.exercises||[]){check(student.includes(`id="${ex.id}"`),`missing student exercise ${ex.id}`);check(sol.includes(`id="${ex.id}"`),`missing solution exercise ${ex.id}`);}}
 for(const n of ["textbook.pdf","solutions.pdf"]){try{const s=(await fs.stat(path.join(project,"dist",n))).size;check(s>10000,`${n} is missing or suspiciously small`)}catch{warnings.push(`${n} not found; run print-pdf.mjs`)}}
 if(warnings.length)console.warn("WARNINGS\n"+warnings.map(x=>"- "+x).join("\n")); if(errors.length){console.error("ERRORS\n"+errors.map(x=>"- "+x).join("\n"));process.exit(strict?1:0)} console.log("verification passed");
}catch(e){console.error(`verify error: ${e.message}`);process.exit(1)}
